os: linux
language: node_js

node_js:
  - "lts/*"
sudo: required

addons:
    apt:
        packages:
            - xvfb
    chrome: stable

services:
  - xvfb

install:
  # https://www.electronjs.org/docs/tutorial/testing-on-headless-ci
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm set progress=false
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run package
  - npm run doc

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
