os: linux
language: node_js

node_js:
  - "node"

addons:
  apt:
    packages:
      - xvfb

services:
  - xvfb

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run package
  - npm run doc

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never