os: linux
language: node_js

node_js:
  - "node"
sudo: required

addons:
    chrome: stable

services:
  - xvfb

install:
  - npm ci

script:
  - npm run lint
  - npm ls got
  - npm run test
  - npm run package
  - npm run doc

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never