# https://github.com/electron-userland/spectron/blob/e0337898825f1a767a1d4243df13cd28ec4ad7cc/.travis.yml
os: linux
dist: trusty
language: node_js
node_js: '12'
sudo: required

addons:
  chrome: stable

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & 
  - sleep 3 # give xvfb some time to start

install:
  - npm set progress=false
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run package
  - npm run doc

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
