os: osx
language: node_js

node_js:
  - "lts/*"
sudo: required

addons:
    chrome: stable

before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - npm set progress=false
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run package
  - npm run doc

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
